name: canvas_grid
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/holyboom1/canvas_grid

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  defer_pointer: ^0.0.2
  r_tree: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



